name: openvswitch
version: 2.12.0
summary: Open vSwitch
description: |
  Open vSwitch is a production quality, multilayer, software-based,
  Ethernet virtual switch. It is designed to enable massive network
  automation through programmatic extension, while still supporting
  standard management interfaces and protocols (e.g. NetFlow, IPFIX,
  sFlow, SPAN, RSPAN, CLI, LACP, 802.1ag). In addition, it is designed
  to support distribution across multiple physical servers similar to
  VMware's vNetwork distributed vswitch or Cisco's Nexus 1000V.
grade: devel
confinement: strict
base: core18
environment:
  OVS_LOGDIR: $SNAP_COMMON/log/openvswitch
  OVS_RUNDIR: $SNAP_COMMON/run/openvswitch
  OVS_SYSCONFDIR: $SNAP_COMMON/etc
  OVS_PKGDATADIR: $SNAP/share/openvswitch
  OVS_BINDIR: $SNAP/bin
  OVS_SBINDIR: $SNAP/sbin

apps:
  ovs-vswitchd:
    command: share/openvswitch/scripts/ovs-ctl --no-ovsdb-server --no-monitor --system-id=random start
    stop-command: share/openvswitch/scripts/ovs-ctl --no-ovsdb-server stop
    daemon: forking
    passthrough:
      after: [ovsdb-server]
    plugs:
      - network
      - network-bind
      - network-control
      - openvswitch-support
      - process-control
      - system-trace
  ovsdb-server:
    command: share/openvswitch/scripts/ovs-ctl --no-ovs-vswitchd --no-monitor --system-id=random start
    stop-command: share/openvswitch/scripts/ovs-ctl --no-ovs-vswitchd stop
    daemon: forking
    plugs:
      - network
      - network-bind
      - network-control
      - openvswitch-support
      - process-control
      - system-trace
  ovs-vsctl:
    command: ovs-vsctl
    plugs:
      - network
  ovs-appctl:
    command: ovs-appctl
    plugs:
      - network
  ovs-ofctl:
    command: ovs-ofctl
    plugs:
      - network
  ovs-dpctl:
    command: ovs-dpctl
    plugs:
      - network

parts:
  openvswitch:
    source: http://openvswitch.org/releases/openvswitch-$SNAPCRAFT_PROJECT_VERSION.tar.gz
    plugin: autotools
    build-packages:
      - libssl-dev
      - libnuma-dev
      - libcap-ng-dev
      - libpcap-dev
      - libunbound-dev
      - python-all
      - python-six
      - python-setuptools
    stage-packages:
      - uuid-runtime
      - libevent-2.1-6
      - libunbound2
    configflags:
      - "--localstatedir=/var/snap/$SNAPCRAFT_PROJECT_NAME/common"
      - "--sysconfdir=/var/snap/$SNAPCRAFT_PROJECT_NAME/etc"
